### ISSUE TITLE
Get Started & Read Docs Button Not responding

### ISSUE THREAD

**Issue by mayankmehta19032003** [saurabhmehta1601/local-custom-domains#6]
When I click on the "Read Docs" button, nothing appears to happen, and no content is displayed.

If this feature is still under development, I suggest adding a notification or message to inform users that the feature is currently unavailable.

Here is the screenshoot of button : 
![Screenshot 2024-10-05 161314](https://github.com/user-attachments/assets/408f0dfa-479a-40bb-b260-535408173c97)

**Comment by saurabhmehta1601** [comment]
This feature in under development
